# Site settings
title: Kadie Jaffe
email: kadie@berkeley.edu
url: https://kadie16.github.io
description: " Kadie Jaffe "

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000' #801A4C
  links: '#219ab3'

# Footer settings
footer: Kadie Jaffe

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://linkedin.com/kadiejaffe
  - title: github
    url: https://github.com/kadie16

# Build settings
markdown: kramdown
permalink: pretty
