# Site settings
title: 'Kadie Jaffe'

baseurl: '' # the subpath of your site, e.g. /blog
url: 'http://kadie16.github.io' # the base hostname & protocol for your site

# emojii
# must comment these out for jekyll for now, can fix later by updating github pages 
#gems:
# - jemoji

# Build settings
markdown:            kramdown
relative_permalinks: false
permalink:           :title/

pagination:          true
paginate:            6
paginate_path:       page/:num/

sass:
    sass_dir: _sass
    style:    compressed

defaults:
  -
      scope:
        path: '_posts'
        type: 'posts'
      values:
        reading_time: true
        # Meta
        show_tags: true
        show_categories: true
        # Social
        share_buttons: true
        disqus: true

